### ISSUE TITLE
Language Translation Option

### ISSUE THREAD

**Issue by Kaakyire9** [Kaakyire9/Project1-Diveristy-Inclusion#8]
**User story:** 
As a non-native English speaker, I could have the option to translate the page content into different languages so that I can fully understand the information.

**Acceptance Criteria:**

- [ ] Page includes option to translate content into at least 3 other languages
- [ ] Translation maintains layout and functionality of the page
- [ ] Translation option is easy to find and use

**Tasks:**

- [ ] Research and implement translation API or service
- [ ] Design language selection interface
- [ ] Test translations for accuracy and layout integrity
- [ ] Ensure translation option is accessible and responsive
